#DATABASE
DATABASE_MASK = '../applicationDatabase.db'
DATABASE = 'applicationDatabase.db'

DATABASE_SHARED = 'sharedDB.db'

TABLE_USERS = 'users'
TABLE_ENTRIES = 'entries'

#VALIDATION STUFF
MAX_LOGIN_ATTEMPTS = 3
LENGTH_VALIDATION_CODE = 8

#Telegram Bot token
BOT_TOKEN = '166998703:AAGvk0No3abHbGc9LpUpJko7WTx1DR9jURY'

# Code creation
RANDOM_CONFIRMATION_CODE_LENGTH = 6

